---
title: "Concentration-Response Modeling for 2D Rat NFA data from Frank et al., 2018"
author: Sierra Boyd
output:
  html_document:
    theme: cerulean
    toc: false
    code_folding: hide
editor_options: 
  chunk_output_type: console
---
```{r load packages}

library(tidyverse)
library(dplyr)
library(tidyr)
library(magrittr)
library(ggplot2)
library(ggpubr)
library(ggpattern)
library(tcpl)
library(tcplfit2)
library(stringr)
library(data.table)
library(openxlsx)
library(readxl)
library(conflicted)
library(pracma)
library(pheatmap)

conflicts_prefer(purrr::transpose())
conflicts_prefer(dplyr::filter())

```

```{r}
setwd("~")

```

```{r}
project.input.dir <-"~"

#make a vector of csv file names
csv_files<- list.files(path=project.input.dir, pattern = "CF_All_Data\\.csv$", recursive = T, full.names = T) 

#import files
for (i in csv_files){
  df<-fread(i)
  full_data<-df
}

#edit names
setnames(full_data,"treatment","trt")

#filter to only include common compounds
full_data <-full_data%>% dplyr:: filter((trt == "Dieldrin")|
                                  (trt =="Deltamethrin")|
                                   (trt=="Loperamide")|
                                   (trt=="Glyphosate")|
                                  (dose==0))

#Edit the trt column to make dose 0 called controls
full_data<-full_data%>%mutate(trt = ifelse(dose == 0, "Control", trt))

#check for duplicates and remove
full_data<-full_data%>%distinct(date,Plate.SN,DIV,well,trt,dose,units,.keep_all=TRUE)

#update endpoint name
setnames(full_data,"mi","Mutual.Information")

#melt to a long data fromat
fulldata_melt <- melt(full_data, id.vars = c("Plate.SN","DIV","trt","dose","well"),
                          measure.vars =c("meanfiringrate","burst.per.min","mean.isis","per.spikes.in.burst","mean.dur","mean.IBIs","nAE","nABE","ns.n","ns.peak.m","ns.durn.m","ns.percent.of.spikes.in.ns","ns.mean.insis","ns.durn.sd","ns.mean.spikes.in.ns","r","Mutual.Information"))

#update names
setnames(fulldata_melt,"variable","Endpoint")
setnames(fulldata_melt,"value","rval")

#set any NAs to 0
fulldata_melt <- fulldata_melt %>% 
                      mutate(rval = replace_na(rval, 0))

```


#Calculate the AUC for each endpoint, treatment, and dose
```{r}
#arange DIVs and calucalte AUC
auc_df<-fulldata_melt %>%
  group_by(trt,Endpoint, dose, Plate.SN,well) %>%
  arrange(DIV)%>%
  summarize (AUC=trapz(DIV,rval))%>%
  ungroup()


```

#Prepare data for concentration-response modelin with tcplfit2
```{r}
#set any dose=0 to very small number like 0.0001 
auc_df <- as.data.frame(sapply(auc_df, function(dose) ifelse(dose == 0, "0.0001", as.character(dose))))

#set as a data table 
auc_df<-as.data.table(auc_df)

#check tha variables are numeric
auc_df$dose<-as.numeric(auc_df$dose)
auc_df$AUC<-as.numeric(auc_df$AUC)

#mke a binary column called wllt. Where N=non-treated and t=treated
auc_df <- auc_df[, wllt := ifelse(dose %in% 0.0001, 'n','t')]

#Each chemical replicate is on its own plate and for every endpoint
auc_df[,bval:=median(AUC[wllt=='n']),by=c("Endpoint","Plate.SN")]

#check of NAs and remove
bval.na <- auc_df[is.na(bval),]
auc_df <- auc_df[!is.na(bval),]

#normalize data to baseline values
auc_df <- auc_df[,resp := ((AUC - bval) / bval)* 100]

#calculate bmad (baseline median absolute deviation) for every endpoint
auc_df[, bmad := mad(resp[wllt %in% 'n']), by=c("Endpoint")]

#check for NAs and remove
auc_df <- auc_df[!is.na(bmad),]

#set cut off value to 3*bmad (this is historic for NFA assays)
auc_df[, coff := 3*bmad] 

#calculate standard deviation for each endpoint
auc_df[, onesd := sd(resp[wllt %in% 'n']), by=Endpoint]

#update variable names
setnames(auc_df,"Endpoint","acnm")
setnames(auc_df,"AUC","rval")

#filter to remove controls for curve fiting
auc_df<-subset(auc_df %>% filter(!grepl("Control",trt)))

#check for duplicates and remove
auc_df<-auc_df%>%distinct(trt,acnm,dose,Plate.SN,well,.keep_all=TRUE)

```

```{r}
# create empty vectors
res <- data.frame()
datalist <- list()


for(i in 1:length(unique(auc_df$acnm))){
  this.aenm <- unique(auc_df$acnm)[i]
  aenm.temp <- auc_df[acnm == this.aenm, ]
  #aenm.temp[, aenm := this.aenm]
  for(j in 1:length(unique(aenm.temp$trt))){ # used ii so that i isn't being overwritten
    this.trt <- unique(aenm.temp$trt)[j]
    this.apid <- unique(aenm.temp[trt %in% this.trt, Plate.SN]) # need to subset by apid
    temp <- aenm.temp[trt == this.trt | (Plate.SN %in% this.apid & wllt %in% 'n'), ]
    temp[, trt := trt]
    row = list(conc=temp$dose, # use conc from the subset
               resp=temp$resp, # use resp from the subset, note from 03/04/2024: resp is not getting updated by chemical it's all the same for each row
               bmed= 0, # 0 since we are working with a normalized percent scale
               cutoff= unique(temp$coff), # find cutoff using 3bmad for EACH aenm (i)
               # cutoff= unique(temp$coff), # find cutoff using 3bmad for EACH aenm (i)
               onesd= unique(temp$onesd), # find sd for EACH aenm (i)
               name= this.trt, # update here as well
               assay= unique(temp$acnm)) # instead of assay we can use this to identify the endpoint for each curve fit 
    # run concentration-response modeling (1st plotting option)
    out = concRespCore(row,
                       fitmodels = c("cnst", "hill", "gnls", "poly1", "poly2", "pow", "exp2", "exp3", "exp4",
                                     "exp5"),conthits=TRUE,do.plot=FALSE)
    datalist[[j]] <- out
    res1 <- do.call(rbind, datalist)
  }  
  res <- rbind(res, res1)
}
setDT(res)
res[, hitc := ifelse(hitcall>=0.9,1,0)]
res[hitc==1, c('name','assay')] 

# save res file as an excel
write.xlsx(res, './20240920_Axion_Res.xlsx')

file.dir <- paste("~", sep="")
file.name <- paste0("/CF_tcplfit2_curves", Sys.Date(), ".pdf", sep="")
file.path <- paste(file.dir, file.name, sep="")
dir.create(path=file.dir, showWarnings = FALSE, recursive = TRUE)
pdf(file.path, 
    width = 12, 
    height = 10)
# plot results using `concRespPlot`(2nd plotting option)
for(i in 1:nrow(res)){
  concRespPlot(res[i,],ymin=-100,ymax=1000) 
}

dev.off()

```

#Prep Data for Up down heatmap
```{r}
write.csv(res,file = "~")


#select needed columns only
heatmap_data<-select(res, c("name","assay","ac50", "hitcall"))

#update column names
setnames(heatmap_data,"name","trt")
setnames(heatmap_data,"assay","acnm")

#Find log 10
heatmap_data$log10<-log10(heatmap_data$ac50)

#remove any log10 values that have hitcalls less than .9
heatmap_data$log10[heatmap_data$hitcall<0.9]<-4

#select only needed columns
heatmap_data<-select(heatmap_data, c("trt","acnm","log10"))

#check that log10 values are numeric
heatmap_data$log10<-as.numeric(heatmap_data$log10)

#Pivot to wide data format
heatmap_wide<-heatmap_data%>%
  pivot_wider(names_from=acnm,values_from=log10) %>%
  column_to_rownames(var="trt")

#Create a Matrix
heatmap_wide<-as.matrix(heatmap_wide)

```

#Plot log10 (AC50) values
```{r}
color.divisions <- 100

#Plot
AUC_AC50<-pheatmap(heatmap_wide,
                           cluster_rows=T,
                           cluster_cols=T,
                           na.color="grey90",
                           color = colorRampPalette(c("firebrick","orangered","orange","grey90"))(100),
                                               main="2D Rat Network Formation Assay",
                           breaks = seq(-3,4, length.out=(color.divisions + 1)))
          

AUC_AC50

#save
ggsave("AUC_AC50_heatmap.png",plot=AUC_AC50,bg="white",width=7,height=5.5)
```