---
title: "Selected Activity/Network Endpoints versus selected Action Potential Propagation Correlations"
author: Sierra Boyd
output:
  html_document:
    theme: cerulean
    toc: false
    code_folding: hide
editor_options: 
  chunk_output_type: console
---
```{r load packages}

library(tidyverse)
library(dplyr)
library(tidyr)
library(readxl)
library(pracma)
library(conflicted)
library(data.table)
library(pheatmap)
library(corrplot)


conflicts_prefer(dplyr::filter())

```

#Load activty and network data
```{r}
#Load Axon data 
#set wd to an export folder
setwd("C:/Users/sboyd01/OneDrive - Environmental Protection Agency (EPA)/Profile/Documents/Project-Chronic DNT Organoid/Data Analysis/Axon Tracking/Exported Files")
getwd()

#Indicate input directory
project.input.dir <-"C:/Users/sboyd01/OneDrive - Environmental Protection Agency (EPA)/Profile/Documents/Project-Chronic DNT Organoid/Data Analysis/Axon Tracking"

#Make list of data files 
csv_files<- list.files(path=project.input.dir, pattern = "_Melt\\.csv$", recursive = T, full.names = T) 

#Make vector for what the names of the basenames of the data files
data_frame_names<-gsub("_Melt.csv","",basename(csv_files))

#load data and remove extra columns
for (i in csv_files){
  df<-fread(i)
  df<-df[,-1]
  Axon<-df
}

#Load Network data
#Indicate input directory
project.input.dir <-"C:/Users/sboyd01/OneDrive - Environmental Protection Agency (EPA)/Profile/Documents/Project-Chronic DNT Organoid/Data Analysis/Network Analysis"

#Make list of data files 
csv_files<- list.files(path=project.input.dir, pattern = "_Melt\\.csv$", recursive = T, full.names = T) 

#Make vector for what the names of the basenames of the data files
data_frame_names<-gsub("_Melt.csv","",basename(csv_files))

#load data and remove extra columns
for (i in csv_files){
  df<-fread(i)
  df<-df[,-1]
  df<-df[,-8]
  Network<-df
}

#Load Activity Data
#Indicate input directory
project.input.dir <-"C:/Users/sboyd01/OneDrive - Environmental Protection Agency (EPA)/Profile/Documents/Project-Chronic DNT Organoid/Data Analysis/Activity Analysis"

#Make list of data files 
csv_files<- list.files(path=project.input.dir, pattern = "_Melt\\.csv$", recursive = T, full.names = T) 

#Make vector for what the names of the basenames of the data files
data_frame_names<-gsub("_Melt.csv","",basename(csv_files))

#load data and remove extra columns
for (i in csv_files){
  df<-fread(i)
  df<-df[,-1]
  Activity<-df
}

```

#Wrangle data and plot all network and activity endpoints
```{r}
#Need to calculate AUC for activity/network and action potnetial data separate since different DOPs for recordings
#row bind activity and network data into one df
Act_Net <- rbind(Activity,Network)

#filter to only include controls
Act_Net<-subset(Act_Net %>% filter(grepl("Control",Dosage)))

#remove NAs
Act_Net <- Act_Net[!is.na(Act_Net$value),]

#arrange DOPs and calculate area under the curve
Act_Net<-Act_Net %>%
  group_by(Endpoint,Group_ID) %>%
  arrange(DOP)%>%
  summarize (AUC=trapz(DOP,value))%>%
  ungroup()

#remove any NAs
Act_Net <- Act_Net[!is.na(Act_Net$AUC),]

#Axon Data
#filter to only include controls
Axon<-subset(Axon %>% filter(grepl("Control",Dosage)))

#remove NAs
Axon <- Axon[!is.na(Axon$value),]

#arrange DOPs and calculate area under the curve
Axon<-Axon %>%
  group_by(Endpoint,Group_ID) %>%
  arrange(DOP)%>%
  summarize (AUC=trapz(DOP,value))%>%
  ungroup()

#remove NAs
Axon <- Axon[!is.na(Axon$AUC),]

#bind all data together
All<-rbind(Axon,Act_Net)

#edit endpoint names
All$Endpoint<-gsub("ISI_mean","Inter-Spike-Interval (ms)",All$Endpoint)
All$Endpoint<-gsub("activeArea","Active Area",All$Endpoint)
All$Endpoint<-gsub("amplitude_mean","Spike Amplitude (µM)",All$Endpoint)
All$Endpoint<-gsub("firingRate_mean","Firing Rate (Hz)",All$Endpoint)
All$Endpoint<-gsub("Duration","Cluster Duration (ms)",All$Endpoint)
All$Endpoint<-gsub("burstDur","Burst Duration (ms)",All$Endpoint)
All$Endpoint<-gsub("BurstFreq","Burst Frequency (Hz)",All$Endpoint)
All$Endpoint<-gsub("BurstPeak_Mean","Burst Peak (Hz)",All$Endpoint)
All$Endpoint<-gsub("CountsperCluster","Number of Bursts per Cluster",All$Endpoint)
All$Endpoint<-gsub("IBI","Inter-Burst-Interval (ms)",All$Endpoint)
All$Endpoint<-gsub("ICI","Inter-Cluster-Interval (ms)",All$Endpoint)
All$Endpoint<-gsub("SPB_Mean","Number of Spikes per Burst",All$Endpoint)
All$Endpoint<-gsub("ClusterFreq","Cluster Frequency (Counts/min)",All$Endpoint)
All$Endpoint<-gsub("branchLen_mean_branch","Branch Length (µm)-Branch",All$Endpoint)
All$Endpoint<-gsub("branchConductionVel_mean_branch","Conduction Velocity (m/s)-Branch",All$Endpoint)
All$Endpoint<-gsub("conductionVelFit_mean_branch","Conduction Velocity Coefficient of Variation-Branch",All$Endpoint)
All$Endpoint<-gsub("latFromInitSite_mean_branch","Latency from Initation Site Velocity (ms)-Branch",All$Endpoint)
All$Endpoint<-gsub("distFromInitSite_mean_branch","Distance from Initation Site (µm)-Branch",All$Endpoint)
All$Endpoint<-gsub("neuronFiringRate_mean_branch","Firing Rate (Hz)-Branch",All$Endpoint)
All$Endpoint<-gsub("spikesNoPerConfig_mean_mean_branch","Number of Spikes per Configuration-Branch",All$Endpoint)
All$Endpoint<-gsub("completeness_mean_branch","Completeness-Branch",All$Endpoint)
All$Endpoint<-gsub("fisherProjectionDistance_mean_branch","Fisher Projection Distance-Branch",All$Endpoint)
All$Endpoint<-gsub("neuronConductionVel_mean_neuron","Conduction Velocity (m/s)-Neuron",All$Endpoint)
All$Endpoint<-gsub("totalAllLen_mean_neuron","Total All Length (µm)-Branch",All$Endpoint)
All$Endpoint<-gsub("longestBranchLen_mean_neuron","Longest Branch Length (µm)-Neuron",All$Endpoint)
All$Endpoint<-gsub("longestDistFromInitSite_mean_neuron","Longest Distance from Initation Site (µm)-Neuron",All$Endpoint)
All$Endpoint<-gsub("longestLat_mean_neuron","Longest Latency (ms)-Neuron",All$Endpoint)
All$Endpoint<-gsub("amplitudeInitSite_mean_neuron","Amplitude at Initiaiton Site (Hz)-Neuron",All$Endpoint)
All$Endpoint<-gsub("totNoSpikes_mean_neuron","Number of Spikes per Neuron-Neuron",All$Endpoint)
All$Endpoint<-gsub("neuronFiringRate_mean_neuron","Firing Rate (Hz)-Neuron",All$Endpoint)
All$Endpoint<-gsub("totNoSpikes_mean_branch","Number of Spikes-Branch",All$Endpoint)
All$Endpoint<-gsub("silhouetteScore_mean_branch","Silhouette Score-Branch",All$Endpoint)

#indicate selected endpoitns
Selected_Endpoints<-c("Active Area","Firing Rate (Hz)","Cluster Duration (ms)","Burst Peak (Hz)","Inter-Cluster-Interval (ms)","Conduction Velocity (m/s)-Neuron","Number of Spikes per Neuron-Neuron","Longest Distance from Initation Site (µm)-Neuron")

#filter for selected endpoints only
All<-All%>%filter(Endpoint %in% Selected_Endpoints)

#make a wide data format
All_wide<-All%>%
  pivot_wider(names_from=Endpoint,values_from=AUC)

#Check for NAs
All_wide <- All_wide[!is.na(All_wide$'Conduction Velocity (m/s)-Neuron'),]

#make values numeric
All_wide[]<-lapply(All_wide,as.numeric)

#remove identifier columns
All_wide<-All_wide[,-1]

#generate pearson correlation matrix
cor_matrix<-cor(All_wide, method="pearson")

#indicate activity/network endpoints
Act_Net_Endpoints<-c("Active Area","Firing Rate (Hz)","Cluster Duration (ms)","Burst Peak (Hz)","Inter-Cluster-Interval (ms)")

#copy correlation matrix to new matrix name to avoid saving over
cor_matrix_ATypes<-cor_matrix

#Make the rows of the matrix only be the axon potential endpoints
cor_matrix_ATypes<-cor_matrix_ATypes[setdiff(rownames(cor_matrix_ATypes),Act_Net_Endpoints),]

#set as a data frame
cor_matrix_ATypes<-as.data.frame(cor_matrix_ATypes)

#make the columns of the matrix only be the activity/network endpoints
cor_matrix_ATypes <- cor_matrix_ATypes[, (names(cor_matrix_ATypes) %in% Act_Net_Endpoints)]

#make sure it is a matrix
cor_matrix_ATypes<-as.matrix(cor_matrix_ATypes)

#plot
corrplot(cor_matrix_ATypes,method="color",type="upper",
               cex.axis=0.45,
               col.axis="black",
               tl.cex=0.62,
               tl.col="black",
               tl.srt=45)
#manually save as PNG

```



