---
title: "Random Forest Analysis"
author: Sierra Boyd
output:
  html_document:
    theme: cerulean
    toc: false
    code_folding: hide
editor_options: 
  chunk_output_type: console
---
```{r load packages}

library(tidyverse)
library(dplyr)
library(tidyr)
library(readxl)
library(pracma)
library(conflicted)
library(data.table)
library(pheatmap)
library(caret)
library(umap)
library(randomForest)
library(ggpubr)

conflicts_prefer(dplyr::filter())

```

#Import files
```{r}
#Set wd to an export folder
setwd("~")
getwd()

#Load Network data 
#Indicate input directory
project.input.dir <-"~"


#Make list of data files for network scan data
csv_files<- list.files(path=project.input.dir, pattern = "_Melt\\.csv$", recursive = T, full.names = T) 

#import files and remove extra columns
for (i in csv_files){
  df<-fread(i)
  df<-df[,-1]
  df<-df[,-8]
  Network<-df
}

#Load Activity data 
#Indicate input directory
project.input.dir <-"~"

#Make list of data files for activity scan data
csv_files<- list.files(path=project.input.dir, pattern = "Melt\\.csv$", recursive = T, full.names = T) 

#import files and remove extra columns
for (i in csv_files){
  df<-fread(i)
  df<-df[,-1]
  Activity<-df
}

#Load action potential data 
#Indicate input directory
project.input.dir <-"~"

#Make list of data files for activity scan data
csv_files<- list.files(path=project.input.dir, pattern = "Melt\\.csv$", recursive = T, full.names = T) 

#import files and remove extra columns
for (i in csv_files){
  df<-fread(i)
  df<-df[,-1]
  Axon<-df
}
```

#Wrangle data
```{r}
#rowbind activity and network data into one df
Raw_Data <- rbind(Activity,Network)

#Identify plate type for normalization below (24-well plate serial number starts in T, 6-well plate serial number starts in M)
Raw_Data<-Raw_Data%>%
  mutate(Plate_Type=ifelse(grepl("T",Group_ID),"Twenty_four","Six"))

#Set controls to a dose of 0.0001
Raw_Data$Dosage<-gsub("Control",0.0001,Raw_Data$Dosage)
Raw_Data$Dosage<-as.numeric(Raw_Data$Dosage)

#Update chemical name for controls
Raw_Data<-Raw_Data%>%mutate(Chemical = ifelse(Dosage == 0.0001, "Control", Chemical))

#remove NA values
Raw_Data <- Raw_Data[!is.na(value),]

#Calculate AUC, make sure to group and arrange by DOP
auc_df<-Raw_Data %>%
  group_by(Chemical,Endpoint, Dosage,Plate_Type,Group_ID) %>%
  arrange(DOP)%>%
  summarize (AUC=trapz(DOP,value))%>%
  ungroup()


#Identify plate type for normalization below (24-well plate serial number starts in T, 6-well plate serial number starts in M)
Axon<-Axon%>%
  mutate(Plate_Type=ifelse(grepl("T",Group_ID),"Twenty_four","Six"))

#Set controls to a very low dose
Axon$Dosage<-gsub("Control",0.0001,Axon$Dosage)
Axon$Dosage<-as.numeric(Axon$Dosage)

#Update chemical name for controls
Axon<-Axon%>%mutate(Chemical = ifelse(Dosage == 0.0001, "Control", Chemical))

#remove NA values
Axon <- Axon[!is.na(value),]

#Not enougth data for DIV6, remove from analysis
Axon<-Axon%>%filter(
    (!DOP %in% c(6,8,13)))


#Calculate AUC, make sure to group and arrange by DOP
Axon_auc_df<-Axon %>%
  group_by(Chemical,Endpoint, Dosage,Plate_Type,Group_ID) %>%
  arrange(DOP)%>%
  summarize (AUC=trapz(DOP,value))%>%
  ungroup()

#bind all auc data into one
auc_df<-rbind(auc_df,Axon_auc_df)

#set as a data table
auc_df<-as.data.table(auc_df)

#Create Binary column for controls (n=non-treated, t=treated)
auc_df <- auc_df[, wllt := ifelse(Dosage %in% 0.0001, 'n','t')]

#Find the baseline value (bval) or the median of the controls for each endpoint and plate_type
auc_df[,bval:=median(AUC[wllt=='n']),by=c("Endpoint","Plate_Type")]

#Check if there are any na bvals
auc_df <- auc_df[!is.na(bval),]

#Calculate response by normalizing to bval
auc_df <- auc_df[,resp := ((AUC - bval) / bval)* 100]

#Set as numeric or factor
auc_df$Chemical<-as.factor(auc_df$Chemical)
auc_df$Endpoint<-as.factor(auc_df$Endpoint)

#Make a new binary column called class and set 1 for positive compounds and 0 for negative compounds
Positive_Chems<-c("Loperamide","Dieldrin","Deltamethrin")

auc_df<-auc_df%>%
  mutate(Class=ifelse(Chemical %in% Positive_Chems,1,0))

#filter data to only keep the highest 2 concs for each chemical
auc_df<-auc_df%>%
  filter(
    (Chemical=="Dieldrin"& Dosage %in% c(30,10,100))|
    (Chemical=="Deltamethrin"& Dosage %in% c(30,10,100))|
    (Chemical=="Glyphosate"& Dosage %in% c(10,3,30))|
    (Chemical=="Loperamide"& Dosage %in% c(0.03,0.1,0.3,1,3)))

#Check
unique(auc_df$Class) #only 1s and 0s

```

#Make a random forest model
```{r}
#Check for NAs
NA_data<-auc_df[is.na(auc_df$resp)] #no NAs

#Remove NAs if needed
auc_df <- auc_df[!is.na(resp),]

#Remove hitc and hitcall columns
auc_df<-auc_df%>%select(c("Chemical","Endpoint","resp","Dosage","Class","Group_ID"))

#Make a wide data frame, fill table with ac50 values, Endpoints as column names
AUC_wide<-auc_df%>%
  pivot_wider(names_from=Endpoint,values_from=resp) 

#Remove NA rows
AUC_wide<-AUC_wide[apply(AUC_wide,1,function(x)sum(is.na(x))<=0),]

#Set Class as a factor
AUC_wide$Class<-as.factor(AUC_wide$Class)

#Determine which endpoints are the most important by predicting class. Set each endpoint as a predictor variable and add Chemical as an interaction variable 

set.seed(12)
RFmodel<-randomForest(Class~
                      BurstFreq+
                      BurstPeak_Mean+                      
                      ClusterFreq+
                      CountsperCluster+                    
                      Duration+
                      IBI+
                      ICI+
                      ISI_mean+
                      SPB_Mean+
                      activeArea+
                      amplitude_mean+
                      burstDur+
                      firingRate_mean+
                      amplitudeInitSite_mean_neuron+
                      branchConductionVel_mean_branch+
                      branchLen_mean_branch+  
                      completeness_mean_branch+  
                      conductionVelFit_mean_branch+
                      distFromInitSite_mean_branch+
                      fisherProjectionDistance_mean_branch+ 
                      latFromInitSite_mean_branch+
                      longestBranchLen_mean_neuron+
                      longestDistFromInitSite_mean_neuron+
                      longestLat_mean_neuron+
                      neuronConductionVel_mean_neuron+
                      neuronFiringRate_mean_branch+
                      neuronFiringRate_mean_neuron+  
                      silhouetteScore_mean_branch+
                      spikesNoPerConfig_mean_mean_branch+
                      totNoSpikes_mean_branch+
                      totNoSpikes_mean_neuron+
                      totalAxonLen_mean_neuron,
                                     data=AUC_wide,
                                     importance=TRUE)
                                
                                   

RFmodel
#Look at learning curve of model
plot(RFmodel) #look at where the model plateuas to manually set ntrees below

set.seed(845)
RFmodel<-randomForest(Class~
                      BurstFreq+
                      BurstPeak_Mean+                      
                      ClusterFreq+
                      CountsperCluster+                    
                      Duration+
                      IBI+
                      ICI+
                      ISI_mean+
                      SPB_Mean+
                      activeArea+
                      amplitude_mean+
                      burstDur+
                      firingRate_mean+
                      amplitudeInitSite_mean_neuron+
                      branchConductionVel_mean_branch+
                      branchLen_mean_branch+  
                      completeness_mean_branch+  
                      conductionVelFit_mean_branch+
                      distFromInitSite_mean_branch+
                      fisherProjectionDistance_mean_branch+ 
                      latFromInitSite_mean_branch+
                      longestBranchLen_mean_neuron+
                      longestDistFromInitSite_mean_neuron+
                      longestLat_mean_neuron+
                      neuronConductionVel_mean_neuron+
                      neuronFiringRate_mean_branch+
                      neuronFiringRate_mean_neuron+  
                      silhouetteScore_mean_branch+
                      spikesNoPerConfig_mean_mean_branch+
                      totNoSpikes_mean_branch+
                      totNoSpikes_mean_neuron+
                      totalAxonLen_mean_neuron,
                                     data=AUC_wide,
                                     importance=TRUE,
                      ntree=500) # 500 15.38% OOB error
#Confusion matrix:
#  0  1 class.error
#0 8  1  0.11111111
#1 1 14  0.06666667
                                
                                   

RFmodel
plot(RFmodel)


#Check importance plots
importance(RFmodel)
varImpPlot(RFmodel)

#save values as a vector for bar graph later
RFmodel_Importance<-importance(RFmodel)

```

#Evaluate performance of the model with cross validation
```{r}
#Set up a cross-validation procedure (resampling: Cross-Validated (10 fold, repeated 5 times)
train_control<-trainControl(method="repeatedcv",
                            number=10,
                            repeats=5)
set.seed(2424) 
#Train the model with cross validation steps above
Trained_model<-train(Class~BurstFreq+
                      BurstPeak_Mean+                      
                      ClusterFreq+
                      CountsperCluster+                    
                      Duration+
                      IBI+
                      ICI+
                      ISI_mean+
                      SPB_Mean+
                      activeArea+
                      amplitude_mean+
                      burstDur+
                      firingRate_mean+
                      amplitudeInitSite_mean_neuron+
                      branchConductionVel_mean_branch+
                      branchLen_mean_branch+  
                      completeness_mean_branch+  
                      conductionVelFit_mean_branch+
                      distFromInitSite_mean_branch+
                      fisherProjectionDistance_mean_branch+ 
                      latFromInitSite_mean_branch+
                      longestBranchLen_mean_neuron+
                      longestDistFromInitSite_mean_neuron+
                      longestLat_mean_neuron+
                      neuronConductionVel_mean_neuron+
                      neuronFiringRate_mean_branch+
                      neuronFiringRate_mean_neuron+  
                      silhouetteScore_mean_branch+
                      spikesNoPerConfig_mean_mean_branch+
                      totNoSpikes_mean_branch+
                      totNoSpikes_mean_neuron+
                      totalAxonLen_mean_neuron,
                                      data=AUC_wide,
                                      method="rf",
                                      trControl=trainControl(method="repeatedcv"),
                                      importance=TRUE)

#Look at model acuracy
print(Trained_model$results)

Trained_model
plot(Trained_model) #mtry=17, accurarcy = 0.9333333, Kappa=0.8222222

#Make Predictions using the trained model
predictions<-predict(Trained_model,newdata=AUC_wide)

#set up confusion matrix to look at Sensitivity and Specificity 
conf_matrix<-confusionMatrix(predictions,AUC_wide$Class)

print(conf_matrix) #24 true positives and 40 true negatives, no false positives or negatives

#Look at importance values 
importance_values<-varImp(Trained_model,scale=FALSE)

print(importance_values)

Trained_model2<-Trained_model$finalModel

#Extract importance values from the trained model
importance_values<-randomForest::importance(Trained_model2) #four columns (0,1,MeanDecreaseAccuracy,MeanDecreaseGini). First two columns are the mean decrease in accuracy for class 0 (controls) and column 1 is mean decrease accuracy for class 1 (treated)

importance_values

#Shows all interactions and Endpoints
varImpPlot(Trained_model$finalModel)

#look only at only endpoints and not interactions
#Make a importance_values a df
importance_df<-as.data.frame(importance_values)

#make a vector with endpoint names 
Endpoints<-unique(auc_df$Endpoint)

Endpoint_importance_df<-importance_df[rownames(importance_df) %in% Endpoints,]

```

#Graph feature importance results 
```{r}
#Set a new column called Endpoint and paste row names
Endpoint_importance_df$Endpoint<-rownames(Endpoint_importance_df)

#edit endpoint names
Endpoint_importance_df$Endpoint<-gsub("ISI_mean","Inter-Spike-Interval (ms)",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("activeArea","Active Area",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("amplitude_mean","Spike Amplitude (µM)",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("firingRate_mean","Firing Rate (Hz)",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("Duration","Cluster Duration (ms)",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("burstDur","Burst Duration (ms)",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("BurstFreq","Burst Frequency (Hz)",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("BurstPeak_Mean","Burst Peak (Hz)",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("CountsperCluster","Number of Bursts per Cluster",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("IBI","Inter-Burst-Interval (ms)",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("ICI","Inter-Cluster-Interval (ms)",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("SPB_Mean","Number of Spikes per Burst",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("ClusterFreq","Cluster Frequency (Counts/min)",Endpoint_importance_df$Endpoint)

Endpoint_importance_df$Endpoint<-gsub("branchLen_mean_branch","Branch Length (µm)-Branch",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("branchConductionVel_mean_branch","Conduction Velocity (m/s)-Branch",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("conductionVelFit_mean_branch","Conduction Velocity Coefficient of Variation-Branch",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("latFromInitSite_mean_branch","Latency from Initation Site Velocity (ms)-Branch",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("distFromInitSite_mean_branch","Distance from Initation Site (µm)-Branch",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("neuronFiringRate_mean_branch","Firing Rate (Hz)-Branch",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("spikesNoPerConfig_mean_mean_branch","Number of Spikes per Configuration-Branch",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("completeness_mean_branch","Completeness-Branch",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("fisherProjectionDistance_mean_branch","Fisher Projection Distance-Branch",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("neuronConductionVel_mean_neuron","Conduction Velocity (m/s)-Neuron",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("totalAxonLen_mean_neuron","Total Axon Length (µm)-Branch",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("longestBranchLen_mean_neuron","Longest Branch Length (µm)-Neuron",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("longestDistFromInitSite_mean_neuron","Longest Distance from Initation Site (µm)-Neuron",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("longestLat_mean_neuron","Longest Latency (ms)-Neuron",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("amplitudeInitSite_mean_neuron","Amplitude at Initiaiton Site (Hz)-Neuron",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("totNoSpikes_mean_neuron","Number of Spikes per Neuron-Neuron",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("neuronFiringRate_mean_neuron","Firing Rate (Hz)-Neuron",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("noTotalAnalyzedNeurons_summary","Number of Total Analyzed Neurons-Well",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("neuronConductionVel_mean_summary","Conduction Velocity (m/s)-Well",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("totalAxonLen_mean_summary","Total Axon Length (µm)-Well",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("longestBranchLen_mean_summary","Longest Branch Length (µm)-Well",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("longestDistFromInitSite_mean_summary","Longest Distance from Initation Site Length (µm)-Well",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("longestLat_mean_summary","Longest Latency (ms)-Well",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("amplitudeInitSite_mean_summary","Amplitude at Initation Site (Hz)-Well",Endpoint_importance_df$Endpoint)
Endpoint_importance_df$Endpoint<-gsub("totNoSpikes_mean_branch","Number of Spikes-Branch",Endpoint_importance_df$Endpoint)

Endpoint_importance_df$Endpoint<-gsub("silhouetteScore_mean_branch","Silhouette Score-Branch",Endpoint_importance_df$Endpoint)

#Plot
MeanDecreaseGini_plot<-ggplot(Endpoint_importance_df,aes(x=Endpoint,y=MeanDecreaseGini))+
  geom_bar(stat="identity",position="dodge")+
  theme_minimal()+
  theme(axis.text.x=element_text(angle=90,hjust=1))

MeanDecreaseGini_plot

#double check wd is set to an export folder
setwd("~")

#save
ggsave(MeanDecreaseGini_plot,filename=paste("AllEndpoints_RF_MeanDecreaseGini_plot.png"),height=4.8,width=6.44,unit="in")

#plot
MeanDecreaseAccuracy_plot<-ggplot(Endpoint_importance_df,aes(x=fct_reorder(Endpoint,MeanDecreaseAccuracy),y=MeanDecreaseAccuracy))+
  geom_bar(stat="identity",position="dodge")+
  theme_minimal()+
  ylab("Mean Decrease Accuracy")+
  xlab("Features (Endpoints)")+
  theme(axis.text.x=element_text(angle=90,hjust=1))+
  coord_flip()

MeanDecreaseAccuracy_plot

#save
ggsave(MeanDecreaseAccuracy_plot,filename=paste("AllEndpoints_RF_Accurarcy_plot.png"),height=5.5,width=6.44,unit="in")

#save as a csv
write.csv(Endpoint_importance_df,file = "~",row.names = F)

#Indicate activity/network endpoints
Activity_Network_Endpoints<-c("Inter-Spike-Interval (ms)","Active Area","Spike Amplitude (µM)","Firing Rate (Hz)","Cluster Duration (ms)","Burst Duration (ms)","Burst Frequency (Hz)","Burst Peak (Hz)","Number of Bursts per Cluster","Inter-Burst-Interval (ms)","Inter-Cluster-Interval (ms)","Number of Spikes per Burst","Cluster Frequency (Counts/min)")                            

#isolate activity and network only endpoints here 
Activity_Network_Importance<-Endpoint_importance_df%>%filter(
    (Endpoint %in% Activity_Network_Endpoints))

#isolate action potential endpoints here 
Axon_Importance<-Endpoint_importance_df%>%filter(
    (!Endpoint %in% Activity_Network_Endpoints))

```
